-- MySQL Script generated by MySQL Workbench
-- Wed Sep 21 10:46:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cd` (
  `id_CD` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Manufacturer` VARCHAR(45) NOT NULL,
  `Size` VARCHAR(45) NOT NULL,
  `Cost` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_CD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`genre audio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genre audio` (
  `id_Genre` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Genre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`audio_cd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`audio_cd` (
  `Name` VARCHAR(45) NOT NULL,
  `Album` VARCHAR(45) NOT NULL,
  `Year` VARCHAR(45) NOT NULL,
  `Artist` VARCHAR(45) NOT NULL,
  `Raiting` VARCHAR(45) NOT NULL,
  `cd_id_CD` INT NOT NULL,
  `genre audio_id_Genre` INT NOT NULL,
  PRIMARY KEY (`cd_id_CD`, `genre audio_id_Genre`),
  INDEX `fk_audio_cd_genre audio1_idx` (`genre audio_id_Genre` ASC) VISIBLE,
  CONSTRAINT `fk_audio_cd_cd1`
    FOREIGN KEY (`cd_id_CD`)
    REFERENCES `mydb`.`cd` (`id_CD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audio_cd_genre audio1`
    FOREIGN KEY (`genre audio_id_Genre`)
    REFERENCES `mydb`.`genre audio` (`id_Genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`purveyor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purveyor` (
  `id_Purveyor` INT NOT NULL,
  `Fio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Purveyor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`deal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`deal` (
  `id_Deal` INT NOT NULL,
  `Date` VARCHAR(45) NOT NULL,
  `amount` VARCHAR(45) NOT NULL,
  `Cost` VARCHAR(45) NOT NULL,
  `purveyor_id_Purveyor` INT NOT NULL,
  PRIMARY KEY (`id_Deal`, `purveyor_id_Purveyor`),
  INDEX `fk_deal_purveyor1_idx` (`purveyor_id_Purveyor` ASC) VISIBLE,
  CONSTRAINT `fk_deal_purveyor1`
    FOREIGN KEY (`purveyor_id_Purveyor`)
    REFERENCES `mydb`.`purveyor` (`id_Purveyor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`genre video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genre video` (
  `id Genre` INT NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id Genre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`type program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`type program` (
  `id_Type` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`program` (
  `Name` VARCHAR(45) NOT NULL,
  `Version` VARCHAR(45) NOT NULL,
  `Platform` VARCHAR(45) NOT NULL,
  `Raiting` VARCHAR(45) NOT NULL,
  `Coment` VARCHAR(45) NOT NULL,
  `cd_id_CD` INT NOT NULL,
  `type program_id_Type` INT NOT NULL,
  PRIMARY KEY (`cd_id_CD`, `type program_id_Type`),
  INDEX `fk_program_type program1_idx` (`type program_id_Type` ASC) VISIBLE,
  CONSTRAINT `fk_program_cd1`
    FOREIGN KEY (`cd_id_CD`)
    REFERENCES `mydb`.`cd` (`id_CD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_program_type program1`
    FOREIGN KEY (`type program_id_Type`)
    REFERENCES `mydb`.`type program` (`id_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `id_Client` INT NOT NULL,
  `Fio` VARCHAR(45) NOT NULL,
  `Sum` VARCHAR(45) NOT NULL,
  `Date exp` VARCHAR(45) NOT NULL,
  `Date inp` VARCHAR(45) NOT NULL,
  `Deadline` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Client`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video` (
  `Name` VARCHAR(45) NOT NULL,
  `Year` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `Director` VARCHAR(45) NOT NULL,
  `cd_id_CD` INT NOT NULL,
  `genre video_id Genre` INT NOT NULL,
  PRIMARY KEY (`cd_id_CD`, `genre video_id Genre`),
  INDEX `fk_video_genre video1_idx` (`genre video_id Genre` ASC) VISIBLE,
  CONSTRAINT `fk_video_cd1`
    FOREIGN KEY (`cd_id_CD`)
    REFERENCES `mydb`.`cd` (`id_CD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_genre video1`
    FOREIGN KEY (`genre video_id Genre`)
    REFERENCES `mydb`.`genre video` (`id Genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`cd_has_Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cd_has_Client` (
  `cd_id_CD` INT NOT NULL,
  `Client_id_Client` INT NOT NULL,
  PRIMARY KEY (`cd_id_CD`, `Client_id_Client`),
  INDEX `fk_cd_has_Client_Client1_idx` (`Client_id_Client` ASC) VISIBLE,
  INDEX `fk_cd_has_Client_cd_idx` (`cd_id_CD` ASC) VISIBLE,
  CONSTRAINT `fk_cd_has_Client_cd`
    FOREIGN KEY (`cd_id_CD`)
    REFERENCES `mydb`.`cd` (`id_CD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cd_has_Client_Client1`
    FOREIGN KEY (`Client_id_Client`)
    REFERENCES `mydb`.`Client` (`id_Client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`deal_has_cd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`deal_has_cd` (
  `deal_id_Deal` INT NOT NULL,
  `cd_id_CD` INT NOT NULL,
  PRIMARY KEY (`deal_id_Deal`, `cd_id_CD`),
  INDEX `fk_deal_has_cd_cd1_idx` (`cd_id_CD` ASC) VISIBLE,
  INDEX `fk_deal_has_cd_deal1_idx` (`deal_id_Deal` ASC) VISIBLE,
  CONSTRAINT `fk_deal_has_cd_deal1`
    FOREIGN KEY (`deal_id_Deal`)
    REFERENCES `mydb`.`deal` (`id_Deal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_deal_has_cd_cd1`
    FOREIGN KEY (`cd_id_CD`)
    REFERENCES `mydb`.`cd` (`id_CD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
